Repository GDSC-BSIOTR/Quotes, pull requests merged in 2022-09, with the labels that each got.

#41 Update Quotes.json
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#29 added Quote
  Quotes.json
Labels: hacktober-accepted

#2 Added line 4
  README.md
Labels: hacktoberfest-accepted

#26 add quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#5 Added
  Quotes.json
Labels: hacktoberfest-accepted

#32 added quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#31 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted

#27 Added My Role Model
  Quotes.json
Labels: hacktoberfest-accepted

#14 Upadated
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#28 added new quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#30 added quotes
  Quotes.json
Labels: hacktoberfest-accepted

#3 updated
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#22 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted

#4 updated quote
  Quotes.json
Labels: hacktoberfest-accepted

#1 added line 3
  README.md
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#33 Commite
  Quotes.json
Labels: hacktoberfest-accepted

#7 updated
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#20 Updated
  Quotes.json
Labels: hacktoberfest-accepted

#8 Added a quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#16 Commite
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#19 Added quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#34 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#36 Quotes committed!!
  Quotes.json
Labels: hacktoberfest-accepted

#40 quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#42 added quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#43 added new
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#44 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#45 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#46 Update Quotes.json
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted

#47 added
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#48 sandip maheshwari line 466
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#49 updated quote written by elon musk
  Quotes.json
Labels: hacktober-accepted

#50 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#51 Updated
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#52 J.K Rowling added
  Quotes.json
Labels: hacktoberfest-accepted

#53 Update Quotes.json
  Quotes.json
Labels: hacktober-accepted

#55 Updated Quotes
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#56 update quotes
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#57 updated
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#58 new
  Quotes.json
Labels: hacktober-fest, hacktober-accepted
