Repository GDSC-BSIOTR/Quotes, pull requests merged in 2022-10, with the labels that each got.

#61 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted

#60 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted

#59 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted

#62 Add Alan Turing quote
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#63 Added a quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#64 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#65 Update README.md
  README.md
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#69 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted

#66 added quotes by Abdul Kamal
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#67 Update Quotes.json
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#68 Added Quotes and Corrected Syntax
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#70 Updated Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#71 Added quote
  Quotes.json
Labels: hacktober-accepted

#72 Update Quotes.json
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#73 Added Quotes and corrected syntax
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#74 Added Quote of Isssac Asimov and corrected syntax
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#75 Update Quotes.json
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#76 Added quote and corrected syntax
  Quotes.json
Labels: hacktober-accepted

#77 added new quote
  Quotes.json
Labels: hacktober-accepted

#78 Added a Quote and correct syntax error of a previous quote
  Quotes.json
Labels: hacktober-accepted

#79 Added a Quote
  Quotes.json
Labels: hacktober-accepted

#80 Added Allama iqbal quote ,a Urdu poet.
  Quotes.json
Labels: hacktoberfest-accepted

#81 Added Warren Buffett quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktober-accepted

#82 Update Quotes.json
  Quotes.json
Labels: hacktober-accepted

#83 add quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#84 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#85 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#86 Added quote and corrected syntax
  Quotes.json
Labels: hacktober-accepted

#87 Update Quotes.json with Eleanor Roosevelt quote
  Quotes.json
Labels: hacktober-accepted

#89 Add Sundar Pichai Quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#93 added
  Quotes.json
Labels: hacktoberfest-accepted

#90 Update
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#91 Added Dale Carnegie..
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted

#94 Update Quotes.json
  Quotes.json
Labels: hacktober-accepted

#95 quotes is added
  Quotes.json
Labels: hacktober-accepted

#99 Added quote by Buddha
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#100 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#103 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#105 Added a new quote
  README.md
Labels: hacktoberfest-accepted, hacktober-accepted

#106 lanslord11:formatted and added quote by bradley Cooper
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#107 Added New Quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#108 Added a new quote and fix errors
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#111 quote of sant Gadge baba added on line number 689
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#113 added quote by bhagat singh
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#114 Add Lionel Messi quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#115 Added A qoutes from Gen. Patton
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#116 Added Quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#117 added quotess
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#118 add quote
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#119 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#120 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#121 changes done
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#122 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#124 Added New Quote
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#126 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#127 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#128 Update Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#129 added: "Role Model": "Arjuna - of Mahabharat"
  Quotes.json
Labels: hacktober-fest, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#131 Added a quote
  Quotes.json
Labels: hacktober-accepted

#133 Update Quotes.json
  Quotes.json
Labels: hacktober-accepted

#135 Update Quotes.json
  Quotes.json
Labels: hacktober-accepted

#136 Update Quotes.json
  Quotes.json
Labels: hacktober-accepted

#137 Update Quotes.json
  Quotes.json
Labels: hacktober-accepted

#139 Update Quotes.json
  Quotes.json
Labels: hacktoberfest, hacktoberfest-accepted

#140 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#143 Updated and added new Quote
  Quotes.json
Labels: hacktober-accepted

#145 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#146 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#147 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#148 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#149 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#150 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#152 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#153 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#154 Updated Quotes.json
  Quotes.json
Labels: hacktober-fest, hacktoberfest-accepted, hacktober-accepted

#155 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#156 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#157 added a new Quotes
  Quotes.json
Labels: hacktoberfest-accepted, hacktober-accepted

#160 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted

#158 Update Quotes.json
  Quotes.json
Labels: hacktoberfest-accepted
